package com.cruciform.images;

public enum Picture {
	RIFLE_BULLET,
	ENEMY_BULLET_ELONGATED,
	CRUCIFORM_1,
	PLAYER_SHIP_1,
	PLAYER_SHIP_2,
	PLAYER_SHIP_GOLD,
	ROCKET,
	ROCKET_FAST,
	ROCKET_EXPLOSION,
	SIDE_PANEL,
	BOTTOM_PANEL
}
