package com.cruciform.images;

public enum Picture {
	RIFLE_BULLET,
	ENEMY_BULLET_ELONGATED,
	CRUCIFORM_1,
	CRUCIFORM_WEAPON_CROSS,
	CRUCIFORM_WEAPON_BEAM_VERTICAL,
	CRUCIFORM_WEAPON_BEAM_HORIZONTAL,
	PLAYER_SHIP_1,
	PLAYER_SHIP_2,
	PLAYER_SHIP_GOLD,
	PLAYER_SHIP_EXHAUST_1,
	PLAYER_SHIP_EXHAUST_2,
	PLAYER_SHIP_EXHAUST_3,
	PLAYER_EXHAUST_CROSS,
	PLAYER_EXHAUST_CROSS_2,
	ROCKET,
	ROCKET_FAST,
	ROCKET_EXPLOSION,
	SIDE_PANEL,
	BOTTOM_PANEL,
	WEAPONS_PANEL,
}
